services:
  - type: static_site
    name: body-calculator
    buildCommand: npm install && npm run build
    publishDir: dist
    # Redirect all routes to index.html for client-side routing
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
    # Auto deploy on push to main branch
    autoDeploy: true 
